blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/coding-wisely/laravel-slug-auto-generator/discussions/categories/q-a
    about: Ask the community for help
  - name: Request a feature
    url: https://github.com/CodingWisely/laravel-slug-auto-generator/discussions/ideas
    about: Share ideas for new features
  - name: Report a security issue
    url: https://github.com/CodingWisely/laravel-slug-auto-generator/security/policy
    about: Learn how to notify us for sensitive bugs
